name: "Contensis cli action"
description: "A GitHub Action for interacting with a Contensis CMS via the cli"
author: "Zengenti"
branding:
  icon: "terminal"
  color: "blue"
inputs:
  alias:
    description: "The Contensis cloud alias to connect to"
    required: true
  project-id:
    description: "The id of the project to connect to"
    required: false
    default: website
  client-id:
    description: "Client id to connect to the supplied alias"
    required: true
  shared-secret:
    description: "Shared secret to use with the supplied client id"
    required: true
  command:
    description: "Optional: which cli command to run"
    required: false
  cli-version:
    description: "Optional: pull cli from specified tag. Default: release"
    default: release
  cli-splash:
    description: "Optional: show welcome splash screen. Default: true"
    default: true

outputs:
  command-output:
    description: "The cli command output"
    value: ${{ steps.set.outputs.command-output }}

runs:
  using: "composite"
  steps:
    - name: Touch output file
      id: pwd
      shell: bash
      run: |
        touch ./output.json
        echo "pwd=$(pwd)" >> $GITHUB_OUTPUT

    - name: Pull Contensis CLI docker image and run commands
      id: cli-command
      shell: bash
      env:
        CONTENSIS_ALIAS: ${{ inputs.alias }}
        CONTENSIS_PROJECT_ID: ${{ inputs.project-id }}
        CONTENSIS_CLIENT_ID: ${{ inputs.client-id }}
        CONTENSIS_SHARED_SECRET: ${{ inputs.shared-secret }}
        CONTENSIS_COMMAND: ${{ inputs.command || '--help' }}
        CONTENSIS_CLI_SPLASH: ${{ inputs.cli-splash }}
      run: |
        # Export all CONTENSIS_* ,GITHUB_*, and CI env vars to a file
        printenv | grep -E '^(CONTENSIS_|GITHUB_|CI=|HOME=)' > /tmp/github_env

        docker run --rm \
          --env-file /tmp/github_env \
          -v ${{ steps.pwd.outputs.pwd }}/output.json:/usr/src/app/output.json \
          ghcr.io/contensis/cli/main/app:${{ inputs.cli-version }} \
          sh -c '
            [ "$CONTENSIS_CLI_SPLASH" = "true" ] && contensis;
            contensis connect "$CONTENSIS_ALIAS" -id "$CONTENSIS_CLIENT_ID" -s "$CONTENSIS_SHARED_SECRET" -p "$CONTENSIS_PROJECT_ID";
            contensis get version;
            eval contensis $CONTENSIS_COMMAND --output output.json
          '

    - name: Set output variables
      id: set
      shell: bash
      run: |
        {
          echo 'command-output<<EOF'
          cat output.json
          echo 'EOF'
        } >> $GITHUB_OUTPUT
